# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 975563fd1fbf2bd58ce19ca8a81218a7a7b903bab2c7150acfcfe7d4a2e9dafef46842fb67181cfd2fe539eeee197d280fac1de29b48a73037350657f8b4b86e

test:
  secret_key_base: cdb455d818776d90cd102708f4eadad5f958e2d53e632fe1e9f3dafc044dec4538d10328f57a00b27fd57e383470812471eef3e81a911dbe8fe9414914ba1c63

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
